baseURL = "https://bazzicalupo.dev"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]
  title = "Bazzicalupo"
  subtitle = "Boh"
  sections = ["showcase", "about", "education", "experience", "client-and-work", "contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Salvatore"
    text2 = "Bazzicalupo"

  [params.footer]
      copyright = "© Salvatore Bazzicalupo. All rights reserved."